package: jira_knowledgebase_sync
version: '1.0.0'
author: 'Iris Werner'
supportpage: https://github.com/ropaweb/jira_knowledgebase_sync

requires:
    php:
        version: '>=8.4,<9'
    redaxo: ^5.16
    packages:
        yform: "^4"
        cronjob: ">1"

page:
    title: 'translate:jira_knowledgebase_sync.title'
    icon: 'rex-icon fa-arrows-rotate'

pages:
    jira_knowledgebase_sync:
        title: translate:jira_knowledgebase_sync.title
        block: system
        prio: 15
        icon: rex-icon fa-arrows-rotate
        perm: jira_knowledgebase_sync[]
        subpages:
            entry:
                title: translate:jira_knowledgebase_sync.table.entry
                icon: rex-icon fa-document
                perm: jira_knowledgebase_sync[entry]
            category:
                title: translate:jira_knowledgebase_sync.table.category
                icon: rex-icon fa-folder
                perm: jira_knowledgebase_sync[category]
            settings:
                title: translate:jira_knowledgebase_sync.settings
                icon: rex-icon fa-gear
                itemClass: pull-right
                perm: admin
            docs:
                title: translate:jira_knowledgebase_sync.docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemClass: pull-right
                perm: jira_knowledgebase_sync[docs]

default_config:
    api_key: ' '

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
